In [1]:
import pandas as pd
import numpy as np
import ast

In [2]:
df=pd.read_csv(r'C:\Users\Ryzen 5\Desktop\ipl-matches.csv')
df

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [3]:
def countteam():
    df1=pd.read_csv(r'C:\Users\Ryzen 5\Desktop\ipl-matches.csv')
    df1.replace({'Kings XI Punjab':'Punjab Kings','Rising Pune Supergiants':'Rising Pune Supergiant','Delhi Daredevils':'Delhi Capitals','Pune Warriors':'Pune Warriors India'},inplace=True)
    new_df=pd.DataFrame(columns=['Team','Team_Players','count','season','standings'])
    main_df=pd.DataFrame(columns=['Team','Team_Players','count','season','standings'])
    for a in df1['Season'].unique():
        df=df1[df1['Season']==a]
        for i in sorted(df['Team1'].unique()):
            df2=df[(df['Team1']==i) | (df['Team2']==i)]
            l1=[]
            for j in df2[df2['Team1']==i]['Team1Players']:
                l1.append(ast.literal_eval(j))
            l2=[]
            for k in df2[df2['Team2']==i]['Team2Players']:
                l2.append(ast.literal_eval(k))
            tl=l1+l2
            d={}
            for f in range(len(tl)):
                l=[]
                t=sorted(tl[f])
                for g in range(len(tl)):
                    if t==sorted(tl[g]):
                        l.append(g)
                d[tuple(t)]=len(l) 
            new_df=new_df.append({'Team':i,'Team_Players':sorted(d.items(),key=lambda x:x[1],reverse=True)[0][0],'count':sorted(d.items(),key=lambda x:x[1],reverse=True)[0][1],'season':a,'standings':point.loc[i,a]},ignore_index=True)
        main_df=main_df.append(new_df)
    return main_df    
a=countteam()        
a

NameError: name 'point' is not defined

In [ ]:
final=pd.DataFrame(columns=['Team','Team_Players','count','season','standings'])
for i in point.columns[::-1]:
    final=final.append(a.groupby('season').get_group(i).drop_duplicates(keep='first'))
final

In [ ]:
final['standings']=final['standings'].astype('int32')
final

In [ ]:
final['count']=final['count'].astype('int32')
final['count']

In [ ]:
t4=final[final['standings']<5]
t4

In [ ]:
np.corrcoef(t4['count'],t4['standings'])

In [ ]:
t4['standings'].corr(t4['count'],method='pearson')

In [ ]:
import matplotlib.pyplot as plt
plt.scatter(t4['count'],t4['standings'])

In [4]:
point=pd.read_csv(r'C:\Users\Ryzen 5\Desktop\ipl_points_table.csv',header=0).T
point

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
Season & No. of Teams Ho(s) Team,Chennai Super Kings,Delhi Capitals,Kolkata Knight Riders,Mumbai Indians,Punjab Kings,Rajasthan Royals,Royal Challengers Bangalore,Sunrisers Hyderabad,Gujarat Titans,Lucknow Super Giants,Deccan Chargers,Gujarat Lions,Kochi Tuskers Kerala,Pune Warriors India,Rising Pune Supergiant
2007/08,2,4,6,5,3,1,7,NaN,NaN,NaN,8,NaN,NaN,NaN,NaN
2009,4,3,8,7,5,6,2,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN
2009/10,1,5,6,2,8,7,3,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN
2011,1,10,4,3,5,6,2,NaN,NaN,NaN,7,NaN,8,9,NaN
2012,2,3,1,4,6,7,5,NaN,NaN,NaN,8,NaN,NaN,9,NaN
2013,2,9,7,1,6,3,5,4,NaN,NaN,,NaN,NaN,8,NaN
2014,3,8,1,4,2,5,7,6,NaN,NaN,,NaN,NaN,NaN,NaN
2015,2,7,5,1,8,4,3,6,NaN,NaN,,NaN,NaN,NaN,NaN
2016,NaN,6,4,5,8,NaN,2,1,NaN,NaN,,3,NaN,NaN,7
2017,NaN,6,3,1,5,NaN,8,4,NaN,NaN,,7,NaN,NaN,2
2018,1,8,3,5,7,4,6,2,NaN,NaN,,NaN,NaN,NaN,NaN
2019,2,3,5,1,6,7,8,4,NaN,NaN,,NaN,NaN,NaN,NaN
2020,7,2,5,1,6,8,4,3,NaN,NaN,,NaN,NaN,NaN,NaN
2021,1,3,2,5,6,7,4,8,NaN,NaN,,NaN,NaN,NaN,NaN
2022,9,5,7,10,6,2,3,8,1,4,,NaN,NaN,NaN,NaN

In [6]:
point.columns=point.iloc[0,0:]
point=point.iloc[1:]

In [7]:
point=point.T
point

,2007/08,2009,2009/10,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
Season & No. of Teams Ho(s) Team,,,,,,,,,,,,,,,
Chennai Super Kings,2,4,1,1,2,2,3,2,NaN,NaN,1,2,7,1,9
Delhi Capitals,4,3,5,10,3,9,8,7,6,6,8,3,2,3,5
Kolkata Knight Riders,6,8,6,4,1,7,1,5,4,3,3,5,5,2,7
Mumbai Indians,5,7,2,3,4,1,4,1,5,1,5,1,1,5,10
Punjab Kings,3,5,8,5,6,6,2,8,8,5,7,6,6,6,6
Rajasthan Royals,1,6,7,6,7,3,5,4,NaN,NaN,4,7,8,7,2
Royal Challengers Bangalore,7,2,3,2,5,5,7,3,2,8,6,8,4,4,3
Sunrisers Hyderabad,NaN,NaN,NaN,NaN,NaN,4,6,6,1,4,2,4,3,8,8
Gujarat Titans,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
Lucknow Super Giants,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
Deccan Chargers,8,1,4,7,8,,,,,,,,,,
Gujarat Lions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,7,NaN,NaN,NaN,NaN,NaN
Kochi Tuskers Kerala,NaN,NaN,NaN,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Pune Warriors India,NaN,NaN,NaN,9,9,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rising Pune Supergiant,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,2,NaN,NaN,NaN,NaN,NaN

In [ ]:
point.rename(columns={'2020':'2020/21'},inplace=True)
point

In [5]:
def countteam():
    df1=pd.read_csv(r'C:\Users\Ryzen 5\Desktop\ipl-matches.csv')
    point=pd.read_csv(r'C:\Users\Ryzen 5\Desktop\ipl_points_table.csv',header=0).T
    point.columns=point.iloc[0,0:]
    point=point.iloc[1:]
    point=point.T
    point.rename(columns={'2020':'2020/21'},inplace=True)
    df1.replace({'Kings XI Punjab':'Punjab Kings','Rising Pune Supergiants':'Rising Pune Supergiant','Delhi Daredevils':'Delhi Capitals','Pune Warriors':'Pune Warriors India'},inplace=True)
    new_df=pd.DataFrame(columns=['Team','Team_Players','count','season','standings'])
    main_df=pd.DataFrame(columns=['Team','Team_Players','count','season','standings'])
    for a in df1['Season'].unique():
        df=df1[df1['Season']==a]
        for i in sorted(df['Team1'].unique()):
            df2=df[(df['Team1']==i) | (df['Team2']==i)]
            l1=[]
            for j in df2[df2['Team1']==i]['Team1Players']:
                l1.append(ast.literal_eval(j))
            l2=[]
            for k in df2[df2['Team2']==i]['Team2Players']:
                l2.append(ast.literal_eval(k))
            tl=l1+l2
            d={}
            for f in range(len(tl)):
                l=[]
                t=sorted(tl[f])
                for g in range(len(tl)):
                    if t==sorted(tl[g]):
                        l.append(g)
                d[tuple(t)]=len(l) 
            new_df=new_df.append({'Team':i,'Team_Players':sorted(d.items(),key=lambda x:x[1],reverse=True)[0][0],'count':sorted(d.items(),key=lambda x:x[1],reverse=True)[0][1],'season':a,'standings':point.loc[i,a]},ignore_index=True)
        main_df=main_df.append(new_df)
    final=pd.DataFrame(columns=['Team','Team_Players','count','season','standings'])
    for i in point.columns[::-1]:
        final=final.append(main_df.groupby('season').get_group(i).drop_duplicates(keep='first'))
    final['standings']=final['standings'].astype('int32')
    final['count']=final['count'].astype('int32')
    return np.corrcoef(final['count'],final['standings'])
a=countteam()        
a

array([[ 1.        , -0.48766409],
       [-0.48766409,  1.        ]])